### ISSUE TITLE
Question: does it work with SQLAlchemy 1.4 (& 2.0)?

### ISSUE THREAD

**Issue by cibolog** [geoalchemy/geoalchemy2#339]
Haven't tried it myself yet, would it work with the aforementioned versions? And more specifically, with declarative model definitions.

**Comment by mbtronics** [comment]
I had some warnings on 1.4.28, but everything else seemed fine.
See #336

**Comment by adrien-berchet** [comment]
Hi @cibolog 
As far as I know, it is supposed to work with any 1.4.* or 2.* versions, with both the core or ORM models. If you find any issue please report it here.

**Comment by adrien-berchet** [comment]
> Using SQLAlchemy master, I get:
> > ImportError: cannot import name 'with_metaclass' from 'sqlalchemy.util'
> 
> Should I file a separate issue?

Hello @auxsvr,
Thank you for this report.
Yes please submit a new issue so it will be more visible. I will check that later.
